apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"app":"myserver"},"name":"myserver","namespace":"default"},"spec":{"containers":[{"image":"blux2/hello-server:2.4","name":"hello-server","ports":[{"containerPort":8080}]}]}}
  creationTimestamp: "2026-01-27T07:38:37Z"
  labels:
    app: myserver
  name: myserver
  namespace: default
  resourceVersion: "2866"
  uid: 6fdb43d3-00c1-4c73-a22f-39663ad4832d
spec:
  containers:
  - image: blux2/hello-server:2.4
    imagePullPolicy: Always
    name: hello-server
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-22fgh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-22fgh
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-01-27T07:38:39Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-01-27T07:38:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-01-27T07:49:15Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-01-27T07:49:15Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-01-27T07:38:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b1ac23f517cca02ae8477b601c81cfed0d345b925d4ed065c6ae0de98545ddfa
    image: docker.io/blux2/hello-server:2.4
    imageID: docker.io/blux2/hello-server@sha256:7f2afb65fbc913429afaa3bdbe04b1d568d41c2474722959221fdc476f0675d2
    lastState: {}
    name: hello-server
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-01-27T07:49:15Z"
  hostIP: 172.23.0.2
  hostIPs:
  - ip: 172.23.0.2
  phase: Running
  podIP: 10.244.0.6
  podIPs:
  - ip: 10.244.0.6
  qosClass: BestEffort
  startTime: "2026-01-27T07:38:37Z"
