apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver-recreate
  labels:
    app: nginx
spec:
  #複製する数
  replicas: 10 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.28 # 1.29.4 -> 1.28に変更